# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'SmartTvPakistan' do
pod 'MFSideMenu'
pod 'CocoaLumberjack'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'AFNetworking', '~> 3.0'
end

target 'SmartTvPakistanTests' do

end

target 'SmartTvPakistanUITests' do

end

target 'SmartTvPakistan-TV' do
platform :tvos, '9.0'
pod 'CocoaLumberjack'
pod 'AFNetworking', '~> 3.0'
end

target 'SmartTvPakistan-TVTests' do

end

target 'SmartTvPakistan-TVUITests' do

end

target 'SmartTvPakistan-Watch' do
pod 'MFSideMenu'
pod 'CocoaLumberjack'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'AFNetworking', '~> 3.0'
end

target 'SmartTvPakistan-Watch Extension' do

end

